apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
  labels:
      app: app
      name: sql-pod
spec:
  containers: 
    - name: sql
      image: mcr.microsoft.com/mssql/server
      ports: 
        - containerPort: 1433
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "123456@SQL.com.pe"